[2024-10-05T14:07:31.215+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_stages.upload_to_s3 manual__2024-10-05T14:02:10.966912+00:00 [queued]>
[2024-10-05T14:07:31.225+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_stages.upload_to_s3 manual__2024-10-05T14:02:10.966912+00:00 [queued]>
[2024-10-05T14:07:31.226+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-05T14:07:31.227+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-10-05T14:07:31.227+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-05T14:07:31.242+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-10-05 14:02:10.966912+00:00
[2024-10-05T14:07:31.247+0000] {standard_task_runner.py:55} INFO - Started process 13852 to run task
[2024-10-05T14:07:31.250+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pdf_extraction_stages', 'upload_to_s3', 'manual__2024-10-05T14:02:10.966912+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/PDF-ETL.py', '--cfg-path', '/tmp/tmpwo2wyw75']
[2024-10-05T14:07:31.252+0000] {standard_task_runner.py:83} INFO - Job 81: Subtask upload_to_s3
[2024-10-05T14:07:31.275+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-05T14:07:31.352+0000] {task_command.py:389} INFO - Running <TaskInstance: pdf_extraction_stages.upload_to_s3 manual__2024-10-05T14:02:10.966912+00:00 [running]> on host 93d8e18bedbe
[2024-10-05T14:07:31.453+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pdf_extraction_stages
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-05T14:02:10.966912+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-05T14:02:10.966912+00:00
[2024-10-05T14:07:31.613+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/PDF-ETL.py", line 111, in upload_to_s3
    nanonets_s3_key = f'nanonets/{os.path.basename(nanonets_output_path)}'
  File "/usr/local/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-10-05T14:07:31.631+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pdf_extraction_stages, task_id=upload_to_s3, execution_date=20241005T140210, start_date=20241005T140731, end_date=20241005T140731
[2024-10-05T14:07:31.645+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 81 for task upload_to_s3 (expected str, bytes or os.PathLike object, not NoneType; 13852)
[2024-10-05T14:07:31.663+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-05T14:07:31.687+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
