[2024-10-07T06:11:14.760+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pinecone_embedding_test_dag.embed_convertapi_pages manual__2024-10-07T06:11:00.200205+00:00 [queued]>
[2024-10-07T06:11:14.774+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pinecone_embedding_test_dag.embed_convertapi_pages manual__2024-10-07T06:11:00.200205+00:00 [queued]>
[2024-10-07T06:11:14.774+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-07T06:11:14.775+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 3
[2024-10-07T06:11:14.775+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-07T06:11:14.793+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): embed_convertapi_pages> on 2024-10-07 06:11:00.200205+00:00
[2024-10-07T06:11:14.803+0000] {standard_task_runner.py:55} INFO - Started process 6447 to run task
[2024-10-07T06:11:14.806+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pinecone_embedding_test_dag', 'embed_convertapi_pages', 'manual__2024-10-07T06:11:00.200205+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/Pinecone_Test.py', '--cfg-path', '/tmp/tmpr6a493nt']
[2024-10-07T06:11:14.806+0000] {standard_task_runner.py:83} INFO - Job 394: Subtask embed_convertapi_pages
[2024-10-07T06:11:14.837+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-07T06:11:14.954+0000] {task_command.py:389} INFO - Running <TaskInstance: pinecone_embedding_test_dag.embed_convertapi_pages manual__2024-10-07T06:11:00.200205+00:00 [running]> on host 1350c74cd1fb
[2024-10-07T06:11:15.108+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pinecone_embedding_test_dag
AIRFLOW_CTX_TASK_ID=embed_convertapi_pages
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T06:11:00.200205+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-07T06:11:00.200205+00:00
[2024-10-07T06:11:15.146+0000] {connectionpool.py:813} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47ba38b090>: Failed to establish a new connection: [Errno -2] Name or service not known')': /databases
[2024-10-07T06:11:15.149+0000] {connectionpool.py:813} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47ba38b290>: Failed to establish a new connection: [Errno -2] Name or service not known')': /databases
[2024-10-07T06:11:15.152+0000] {connectionpool.py:813} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47ba38b250>: Failed to establish a new connection: [Errno -2] Name or service not known')': /databases
[2024-10-07T06:11:15.155+0000] {logging_mixin.py:137} INFO - Error creating Pinecone index: HTTPSConnectionPool(host='controller.us-east1-aws.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47ba38b450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2024-10-07T06:11:15.180+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_021a5339-744f-42b7-bd9b-9368b3efda7a.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:11:15.181+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_366e2f2b-8632-4ef2-81eb-bc3877489217.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:11:15.183+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_634fca59-03b2-4cdf-9ce4-0205df22f256.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:11:15.186+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_8f697523-6988-4c4f-8d72-760a45681f68.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:11:15.193+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_example.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:11:15.193+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-10-07T06:11:15.216+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=pinecone_embedding_test_dag, task_id=embed_convertapi_pages, execution_date=20241007T061100, start_date=20241007T061114, end_date=20241007T061115
[2024-10-07T06:11:15.260+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-10-07T06:11:15.298+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
