[2024-10-07T06:08:09.495+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pinecone_embedding_test_dag.embed_pymupdf_pages manual__2024-10-07T06:07:54.969546+00:00 [queued]>
[2024-10-07T06:08:09.516+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pinecone_embedding_test_dag.embed_pymupdf_pages manual__2024-10-07T06:07:54.969546+00:00 [queued]>
[2024-10-07T06:08:09.517+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-07T06:08:09.517+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 3
[2024-10-07T06:08:09.518+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-07T06:08:09.540+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): embed_pymupdf_pages> on 2024-10-07 06:07:54.969546+00:00
[2024-10-07T06:08:09.551+0000] {standard_task_runner.py:55} INFO - Started process 6216 to run task
[2024-10-07T06:08:09.556+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pinecone_embedding_test_dag', 'embed_pymupdf_pages', 'manual__2024-10-07T06:07:54.969546+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/Pinecone_Test.py', '--cfg-path', '/tmp/tmpj52icclg']
[2024-10-07T06:08:09.556+0000] {standard_task_runner.py:83} INFO - Job 391: Subtask embed_pymupdf_pages
[2024-10-07T06:08:09.585+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-07T06:08:09.696+0000] {task_command.py:389} INFO - Running <TaskInstance: pinecone_embedding_test_dag.embed_pymupdf_pages manual__2024-10-07T06:07:54.969546+00:00 [running]> on host 1350c74cd1fb
[2024-10-07T06:08:09.831+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pinecone_embedding_test_dag
AIRFLOW_CTX_TASK_ID=embed_pymupdf_pages
AIRFLOW_CTX_EXECUTION_DATE=2024-10-07T06:07:54.969546+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-07T06:07:54.969546+00:00
[2024-10-07T06:08:09.872+0000] {connectionpool.py:813} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47ba385410>: Failed to establish a new connection: [Errno -2] Name or service not known')': /databases
[2024-10-07T06:08:09.876+0000] {connectionpool.py:813} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47ba3858d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /databases
[2024-10-07T06:08:09.880+0000] {connectionpool.py:813} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47ba385890>: Failed to establish a new connection: [Errno -2] Name or service not known')': /databases
[2024-10-07T06:08:09.884+0000] {logging_mixin.py:137} INFO - Error creating Pinecone index: HTTPSConnectionPool(host='controller.us-east1-aws.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47ba385a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2024-10-07T06:08:09.910+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_021a5339-744f-42b7-bd9b-9368b3efda7a.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:08:09.911+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_366e2f2b-8632-4ef2-81eb-bc3877489217.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:08:09.912+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_634fca59-03b2-4cdf-9ce4-0205df22f256.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:08:09.916+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_8f697523-6988-4c4f-8d72-760a45681f68.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:08:09.922+0000] {logging_mixin.py:137} INFO - Failed to process /tmp/pymupdf_example.pdf.json: 

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
[2024-10-07T06:08:09.922+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-10-07T06:08:09.948+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=pinecone_embedding_test_dag, task_id=embed_pymupdf_pages, execution_date=20241007T060754, start_date=20241007T060809, end_date=20241007T060809
[2024-10-07T06:08:09.970+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-10-07T06:08:10.006+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
