[2024-10-04T16:07:22.688+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_stages.upload_to_s3 manual__2024-10-04T16:07:01.707653+00:00 [queued]>
[2024-10-04T16:07:22.698+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_stages.upload_to_s3 manual__2024-10-04T16:07:01.707653+00:00 [queued]>
[2024-10-04T16:07:22.698+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-04T16:07:22.699+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-10-04T16:07:22.699+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-04T16:07:22.712+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-10-04 16:07:01.707653+00:00
[2024-10-04T16:07:22.715+0000] {standard_task_runner.py:55} INFO - Started process 270 to run task
[2024-10-04T16:07:22.717+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pdf_extraction_stages', 'upload_to_s3', 'manual__2024-10-04T16:07:01.707653+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/PDF-ETL.py', '--cfg-path', '/tmp/tmpwgsuzmzn']
[2024-10-04T16:07:22.719+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask upload_to_s3
[2024-10-04T16:07:22.740+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T16:07:22.815+0000] {task_command.py:389} INFO - Running <TaskInstance: pdf_extraction_stages.upload_to_s3 manual__2024-10-04T16:07:01.707653+00:00 [running]> on host 93d8e18bedbe
[2024-10-04T16:07:22.912+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pdf_extraction_stages
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-04T16:07:01.707653+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-04T16:07:01.707653+00:00
[2024-10-04T16:07:23.072+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/PDF-ETL.py", line 109, in upload_to_s3
    nanonets_s3_key = f'nanonets/{os.path.basename(nanonets_output_path)}'
  File "/usr/local/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-10-04T16:07:23.090+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=pdf_extraction_stages, task_id=upload_to_s3, execution_date=20241004T160701, start_date=20241004T160722, end_date=20241004T160723
[2024-10-04T16:07:23.104+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 24 for task upload_to_s3 (expected str, bytes or os.PathLike object, not NoneType; 270)
[2024-10-04T16:07:23.130+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-04T16:07:23.158+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
